trunk/portal/trunk/src/main/java/at/darkdestiny/portal/bean/ErrorBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package at.darkdestiny.portal.bean;

import java.io.PrintWriter;
import java.io.StringWriter;
import java.sql.SQLException;
import java.util.Map;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.ServletException;

/**
 *
 * @author LAZYPAD
 */
@ManagedBean(name = "ErrorBean")
@SessionScoped
public class ErrorBean {  
   public String getStackTrace() {  
      FacesContext context = FacesContext.getCurrentInstance();  
      Map<String, Object> request   
         = context.getExternalContext().getRequestMap();  
      Throwable ex = (Throwable) request.get("javax.servlet.error.exception");  
      StringWriter sw = new StringWriter();  
      PrintWriter pw = new PrintWriter(sw);  
      fillStackTrace(ex, pw);  
      return sw.toString();  
   }  
  
   private static void fillStackTrace(Throwable t, PrintWriter w) {  
      if (t == null) return;  
      t.printStackTrace(w);  
      if (t instanceof ServletException) {  
         Throwable cause = ((ServletException) t).getRootCause();  
         if (cause != null) {  
            w.println("Root cause:");  
            fillStackTrace(cause, w);  
         }  
      } else if (t instanceof SQLException) {  
         Throwable cause = ((SQLException) t).getNextException();  
         if (cause != null) {  
            w.println("Next exception:");  
            fillStackTrace(cause, w);  
         }  
      } else {  
         Throwable cause = t.getCause();  
         if (cause != null) {  
            w.println("Cause:");  
            fillStackTrace(cause, w);  
         }  
      }  
   }  
}  

trunk/portal/trunk/src/main/java/at/darkdestiny/portal/bean/MLBean.java
package at.darkdestiny.portal.bean;

import at.darkdestiny.portal.ML;
import at.darkdestiny.portal.language.LANG;
import at.darkdestiny.portal.language.LANG2;
import java.io.Serializable;
import java.util.Locale;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

@ManagedBean(name = "MLBean")
@SessionScoped
public class MLBean implements Serializable {

    public String getML(String constant) {
        return getML(constant, "");
    }

    public String getMLTitle(String constant) {
        return getML(LANG2.SITES.TITLE.PREFIX) + getML(constant, "");
    }

    public String getUsageAgreementML(String constant) {
        String propertiesFile = "Usageagreement";
        ServiceBean serviceBean = (ServiceBean) FacesContext.getCurrentInstance()
                .getExternalContext().getSessionMap().get("ServiceBean");
        if (serviceBean != null && serviceBean.isLocaleSetManually()) {
            return ML.getMLStr(propertiesFile, constant, serviceBean.getLocale());
        } else {
            Locale locale = FacesContext.getCurrentInstance().getExternalContext().getRequestLocale();
            return ML.getMLStr(propertiesFile, constant, locale);
        }
    }

    public String getMLFromPropertiesFile(String propertiesFile, String constant) {
        return ML.getMLStr(propertiesFile, constant, getLocale());
    }

    public static Locale getLocale() {
        ServiceBean serviceBean = (ServiceBean) FacesContext.getCurrentInstance()
                .getExternalContext().getSessionMap().get("ServiceBean");
        if (serviceBean != null && serviceBean.isLocaleSetManually()) {
            return serviceBean.getLocale();
        } else {
            Locale locale = FacesContext.getCurrentInstance().getExternalContext().getRequestLocale();
            return locale;
        }
    }

    /*
     * As(s) jsf seems to have problems to pass a list of arguments please
     * specify the params seperated by a % 'sign'
     *
     * E.g.: %username%logincount
     *
     */
    public String getML(String constant, String paramsString) {
        return ML.getMLStr(constant, paramsString.split("%"));
    }

    public String getActiveLanguage() {
        return ML.getActiveLanguage();
    }

}

trunk/portal/trunk/src/main/webapp/sites/dataAgreement.xhtml
<?xml version='1.0' encoding='ISO-8859-1' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:rich="http://richfaces.org/rich">

    <h:panelGrid>
        <h:outputText escape="false" value="#{MLBean.getUsageAgreementML('dataagreement_1')}"/>
        <h:outputText escape="false" value="#{MLBean.getUsageAgreementML('dataagreement_2')}"/>
        <h:outputText escape="false" value="#{MLBean.getUsageAgreementML('dataagreement_3')}"/>
        <h:outputText escape="false" value="#{MLBean.getUsageAgreementML('dataagreement_4')}"/>
        <h:outputLink value="resources/basic/images/registrationProcess.png">Registration process</h:outputLink>
    </h:panelGrid>

</html>

trunk/portal/trunk/src/main/webapp/sites/download.xhtml
<ui:composition  template="./index.xhtml"
                 xmlns="http://www.w3.org/1999/xhtml"
                 xmlns:dd="http://java.sun.com/jsf/composite/dd"
                 xmlns:f="http://java.sun.com/jsf/core"
                 xmlns:ui="http://java.sun.com/jsf/facelets"
                 xmlns:h="http://java.sun.com/jsf/html">
    <ui:define name="title">#{MLBean.getMLTitle(ML.lang.sites.download.lbl.download)}</ui:define>
    <ui:define name="content">
        <dd:indexPanelGrid >
            <h:panelGrid style="width: 100%;" headerClass="info_header" columnClasses="info_text">
                <f:facet name="header">
                    <h:outputText value="#{MLBean.getML(ML.lang.sites.download.lbl.download)}"/>
                </f:facet>
                <h:panelGrid style="margin: 0 auto; text-align: left;">
                    <h:outputText escape="false"  value="#{MLBean.getMLFromPropertiesFile('Information', 'download')}"/>
                </h:panelGrid>
            </h:panelGrid>
        </dd:indexPanelGrid>
    </ui:define>
</ui:composition>

trunk/portal/trunk/src/main/webapp/sites/errorDisplay.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:a4j="http://richfaces.org/a4j"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                xmlns:rich="http://richfaces.org/rich">
       <p>  
        To our chagrin, an internal error has occurred in this   
        program. Please contact technical support.  
      </p>  
       <p>  
        If instructed by our support staff, please   
        copy and paste the following report into an email message  
      </p>  
       <h:inputTextarea value="#{ErrorBean.stackTrace}" rows="40" cols="80"  
           readonly="true"/>  
</ui:composition>

trunk/portal/trunk/src/main/webapp/sites/exception.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:a4j="http://richfaces.org/a4j"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                xmlns:rich="http://richfaces.org/rich">
       <p>  
        To our chagrin, an internal error has occurred in this   
        program. Please contact technical support.  
      </p>  
       <p>  
        If instructed by our support staff, please   
        copy and paste the following report into an email message  
      </p>  
       <h:inputTextarea value="#{ErrorBean.stackTrace}" rows="40" cols="80"  
           readonly="true"/>  
</ui:composition>

trunk/portal/trunk/src/main/webapp/sites/footer.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:a4j="http://richfaces.org/a4j"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                xmlns:rich="http://richfaces.org/rich">

    <rich:panel id="FooterBox" styleClass="col-xs-20 col-sm-20 col-md-20 col-lg-20">
        <h:panelGrid columns="5" cellpadding="0" style="margin: 0 auto;" columnClasses="footerColumn,footerColumn,footerColumn,footerColumn,footerColumn" cellspacing="0">

            <h:outputLink target="_new" value="http://www.ibgdb.de/games/1105-dark-destiny/like">
                <h:graphicImage url="http://www.ibgdb.de/assets/magich.gif"/>
            </h:outputLink>
            <h:outputLink target="_new" value="http://www.spreadfirefox.com/?q=affiliates&amp;id=0&amp;t=70">
                <h:graphicImage url="http://sfx-images.mozilla.org/affiliates/Buttons/88x31/get.gif"/>
            </h:outputLink>
            <h:panelGrid columns="2">
                <h:form>
                    <h:outputText value="Theme:  "/>
                    <h:selectOneMenu value="#{ServiceBean.theme}" onchange="submit();">
                        <f:selectItems value="#{ServiceBean.themes}"/>
                    </h:selectOneMenu>
                </h:form>
            </h:panelGrid>
            <h:link value="#{MLBean.getML(ML.lang.sites.footer.lbl.impressum)}" outcome="/sites/impressum" />
            <h:outputLink target="_new" value="http://www.inetsolutions.de/">
                <h:outputText value="Hosted by"/>
                <h:graphicImage style="width: 80px;" url="http://www.inetsolutions.de/sponsoring.jpg"/>
            </h:outputLink>

        </h:panelGrid>
    </rich:panel>

</ui:composition>

trunk/portal/trunk/src/main/webapp/sites/index.xhtml
<ui:composition template="./template.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:a4j="http://richfaces.org/a4j"
                xmlns:dd="http://java.sun.com/jsf/composite/dd"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                xmlns:rich="http://richfaces.org/rich">


    <ui:define name="title">DarkDestiny Portal</ui:define>
    <ui:define name="content">
        <h:graphicImage library="basic" name="images/darkdestiny.gif" />
        <dd:indexPanelGrid rendered="#{!LoginBean.logged}">
            <f:facet name="header">
                <h:outputText value="Login"/>
            </f:facet>
            <ui:include src="/sites/loginmain.xhtml"/>
        </dd:indexPanelGrid>
        <dd:indexPanelGrid>
            <f:facet name="header">
                <h:outputText value="Servers"/>
            </f:facet>
            <ui:include src="/sites/servers.xhtml"/>
        </dd:indexPanelGrid>
        <dd:indexPanelGrid>
            <f:facet name="header">
                <h:outputText value="News"/>
            </f:facet>
            <ui:include src="/sites/news/news.xhtml"/>
        </dd:indexPanelGrid>
        <dd:indexPanelGrid>
            <f:facet name="header">
                <h:outputText value="Info"/>
            </f:facet>
            <ui:include src="/sites/information/info.xhtml"/>
        </dd:indexPanelGrid>
        <br/><br/>
    </ui:define>
    #{LoginBean.setResultMessage("")}
    <br />
</ui:composition>

trunk/portal/trunk/src/main/webapp/sites/informationpanel_deprecated.xhtml
<?xml version='1.0' encoding='ISO-8859-1' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:rich="http://richfaces.org/rich">

    <h:form>
        <rich:dataTable id="infoRounds"  value="#{RoundBean.getRoundsNotFinished()}" var="round">
            <f:facet name="header">
                <rich:column colspan="2">
                    <h:outputLabel value="#{MLBean.getML('informationpanel_lbl_servers')}"/>
                </rich:column>
            </f:facet>
            <rich:column>
                <h:outputText  id="server" value="#{round.name}"/>
            </rich:column>
            <rich:column>
                <h:panelGrid columns="3"  cellpadding="0" cellspacing="0">
                    <a4j:outputPanel rendered="#{round.hasStatus('NOCONNECTION')}">
                        <h:graphicImage id="noconnection" rendered="#{round.hasStatus('NOCONNECTION')}" library="basic" name="images/icon_noconnection.png">
                            <rich:tooltip >
                                <h:outputText value="#{MLBean.getML('round_status_noconnection')}"/>
                            </rich:tooltip>
                        </h:graphicImage>
                    </a4j:outputPanel>
                    <a4j:outputPanel  rendered="#{round.hasStatus('STOPPED')}">
                        <h:graphicImage id="stopped"  rendered="#{round.hasStatus('STOPPED')}"  library="basic" name="images/icon_offline.png">
                            <rich:tooltip >
                                <h:outputText value="#{MLBean.getML('round_status_stopped')}"/>
                            </rich:tooltip>
                        </h:graphicImage>
                    </a4j:outputPanel>
                    <a4j:outputPanel rendered="#{round.hasStatus('RUNNING')}">
                        <h:graphicImage id="running"  rendered="#{round.hasStatus('RUNNING')}"    library="basic" name="images/icon_online.png">
                            <rich:tooltip >
                                <h:outputText value="#{MLBean.getML('round_status_online')}"/>
                            </rich:tooltip>
                        </h:graphicImage>
                    </a4j:outputPanel>
                    <a4j:outputPanel>
                        <h:outputLink value="#{round.url}enter.jsp?user=#{LoginBean.user.userName}&amp;portalPassword=#{RoundBean.getPortalPassword(round.id)}">
                            <h:graphicImage id="join"  rendered="#{round.isPortalPasswordValid()}"   library="basic" name="images/icon_join.png">
                                <rich:tooltip >
                                    <h:outputText value="#{MLBean.getML('round_status_join')}"/>
                                </rich:tooltip>
                            </h:graphicImage>
                        </h:outputLink>
                    </a4j:outputPanel>
                    <a4j:outputPanel rendered="#{round.hasStatus('RUNNING_NOUPDATE')}">
                        <h:graphicImage id="runningnoupdate"  rendered="#{round.hasStatus('RUNNING_NOUPDATE')}"   library="basic" name="images/icon_online.png">
                            <rich:tooltip >
                                <h:outputText value="#{MLBean.getML('round_status_runningnotick')}"/>
                            </rich:tooltip>
                        </h:graphicImage>
                    </a4j:outputPanel><a4j:outputPanel rendered="#{round.hasStatus('RUNNING_NOUPDATE')}">
                        <h:graphicImage id="runningnoupdate_icon"  rendered="#{round.hasStatus('RUNNING_NOUPDATE')}"   library="basic" name="images/icon_noupdate.png">
                            <rich:tooltip >
                                <h:outputText value="#{MLBean.getML('round_status_runningnotick')}"/>
                            </rich:tooltip>
                        </h:graphicImage>
                    </a4j:outputPanel>
                    <a4j:outputPanel  rendered="#{round.hasStatus('REGISTRATION')}">
                        <h:graphicImage id="registration"  rendered="#{round.hasStatus('REGISTRATION')}"   library="basic" name="images/icon_registration.png">
                            <rich:tooltip >
                                <h:outputText value="#{MLBean.getML('round_status_registration')}"/>
                            </rich:tooltip>
                        </h:graphicImage>
                    </a4j:outputPanel>
                    <a4j:outputPanel rendered="#{round.downForMaintenance}">
                        <h:graphicImage id="maintenance" rendered="#{round.downForMaintenance}"   library="basic" name="images/icon_maintenance.png">
                            <rich:tooltip >
                                <h:outputText value="#{MLBean.getML('round_status_maintenance')}"/>
                            </rich:tooltip>
                        </h:graphicImage>
                    </a4j:outputPanel>
                    <h:panelGrid rendered="#{LoginBean.adminLogged}" columnClasses="rightAlign, leftAlign"   class="scroller"  columns="2">
                        <a4j:commandLink rendered="#{LoginBean.adminLogged}" value="" render="infoRounds" action="#{round.changeMaintenance()}">
                            <h:graphicImage rendered="#{LoginBean.adminLogged}" library="basic" name="/images/change.png" />
                        </a4j:commandLink>
                    </h:panelGrid>
                    <h:panelGrid rendered="#{LoginBean.adminLogged}"    class="scroller" columns="1">
                        <a4j:commandLink rendered="#{LoginBean.adminLogged}" value="" render="infoRounds" action="#{round.incrementStatus()}">
                            <h:graphicImage rendered="#{LoginBean.adminLogged}"  library="basic" name="images/up.png"  />
                        </a4j:commandLink>
                        <a4j:commandLink rendered="#{LoginBean.adminLogged}" value="" render="infoRounds" action="#{round.decrementStatus()}">
                            <h:graphicImage rendered="#{LoginBean.adminLogged}"  library="basic" name="images/down.png" />
                        </a4j:commandLink>
                    </h:panelGrid>
                </h:panelGrid>
            </rich:column>
            <rich:column rendered="#{!round.hasStatus('NOCONNECTION')}">
                <h:outputText rendered="#{!round.hasStatus('NOCONNECTION')}"   value="#{round.getUserOnlineCount()}/#{round.getUserCount()}"/>
            </rich:column>
        </rich:dataTable>
        <rich:dataTable rows="4"  value="#{ServiceBean.getLastChanges()}" var="change">
            <rich:column breakRowBefore="true">
                <f:facet name="header">
                    #{MLBean.getML('informationpanel_lbl_lastChanges')}
                </f:facet>
                <h:panelGrid  columns="1" cellpadding="0" cellspacing="0">
                    <h:panelGrid  columns="2"  cellpadding="0" cellspacing="0">
                        <h:graphicImage id="bug" rendered="#{change.isBug()}" library="basic" name="images/bug.png">
                            <rich:tooltip >
                                #{MLBean.getML('informationpanel_lbl_bug')}
                            </rich:tooltip>
                        </h:graphicImage>
                        <h:graphicImage id="task" rendered="#{change.isTask()}" library="basic" name="images/task.png">
                            <rich:tooltip >
                                #{MLBean.getML('informationpanel_lbl_task')}
                            </rich:tooltip>
                        </h:graphicImage>
                        <h:outputText  value="#{ConversionBean.longToDateString(change.date)}"/>
                    </h:panelGrid>
                    <h:panelGrid columns="2" >
                        <h:graphicImage id="taskStatus" library="basic" rendered="#{change.isTask()}"  name="#{ConversionBean.taskStatusToIconName(change.getTaskStatus())}">
                            <rich:tooltip >
                                <h:outputText value="#{ConversionBean.taskStatusToName(change.getTaskStatus())}"/>
                            </rich:tooltip>
                        </h:graphicImage>
                        <h:graphicImage id="bugStatus" library="basic" rendered="#{change.isBug()}"  name="#{ConversionBean.bugStatusToIconName(change.getBugStatus())}">
                            <rich:tooltip >
                                <h:outputText value="#{ConversionBean.bugStatusToName(change.getBugStatus())}"/>
                            </rich:tooltip>
                        </h:graphicImage>
                        <h:panelGrid >
                            <h:outputText value="#{change.name}"/>
                        </h:panelGrid>
                    </h:panelGrid>
                </h:panelGrid>
            </rich:column>
        </rich:dataTable>
        <h:panelGrid  >
            <h:outputLink target="_new" value="http://www.ibgdb.de/games/1105-dark-destiny/like">
                <h:graphicImage url="http://www.ibgdb.de/assets/magich.gif"/>
            </h:outputLink>
            <h:outputLink target="_new" value="http://www.spreadfirefox.com/?q=affiliates&amp;id=0&amp;t=70">
                <h:graphicImage url="http://sfx-images.mozilla.org/affiliates/Buttons/88x31/get.gif"/>
            </h:outputLink>
        </h:panelGrid>
    </h:form>
</html>

trunk/portal/trunk/src/main/webapp/sites/login_deprecated.xhtml
<?xml version='1.0' encoding='ISO-8859-1' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:dd="http://java.sun.com/jsf/composite/dd"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:rich="http://richfaces.org/rich">

    <h:form id="Login">
        <h:panelGrid id="Panel"
                     columns="1">
            <rich:messages id="Message"
                           for="loginPanel" />
        </h:panelGrid>

        <c:if test="#{!LoginBean.logged}">
            <dd:outputText id="notlogged"
                           value="#{ML.lang.sites.login.msg.hello}" params="Gast" />
        </c:if>
        <c:if test="#{LoginBean.logged}">
            <dd:outputText id="logged"
                          value="#{ML.lang.sites.login.msg.hello}" params="#{LoginBean.user.userName}" />
            <h:commandLink id="logout" action="#{LoginBean.logout()}" >
                <dd:outputText  value="#{ML.lang.sites.header.lbl.logout}" />
            </h:commandLink>
        </c:if>
    </h:form>
</html>

trunk/portal/trunk/src/main/webapp/sites/menu_deprecated.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:a4j="http://richfaces.org/a4j"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                xmlns:rich="http://richfaces.org/rich">


    <h:form>
        <ul class="menu_new">
            <li><h:link class="home" value="Dark Destiny" outcome="/sites/index.xhtml"/>
                <ul>
                    <li><h:link class="menuitem" value="#{MLBean.getML('menu_lbl_news')}" outcome="/sites/news/news" /></li>
                    <li><h:link class="menuitem" value="#{MLBean.getML('menu_lbl_info')}" outcome="/sites/information/info" /></li>
                    <li><a class="menu_forum" href="http://www.thedarkdestiny.at/board/index.php" target="new">Forum</a></li>
                    <li><h:link rendered="#{LoginBean.logged}" class="menuitem" value="#{MLBean.getML('menu_lbl_profile')}" outcome="profile" /></li>
                    <c:if test="#{LoginBean.adminLogged}">
                        <li><h:link class="menuadmin" value="#{MLBean.getML('menu_lbl_rounds')}" outcome="/sites/rounds/rounds" /></li>
                        <li><h:link class="menuadmin" value="#{MLBean.getML('menu_lbl_mailing')}" outcome="/sites/admin/mailingList" /></li>
                        <li><h:link class="menuadmin" value="#{MLBean.getML('menu_lbl_users')}" outcome="/sites/admin/users" /></li>
                    </c:if>
                </ul>
            </li>
            <li><a href="#">#{MLBean.getML('menu_lbl_media')}</a>
                <ul>
                    <li><h:link class="menuitem" value="#{MLBean.getML('menu_lbl_screenshots')}" outcome="/sites/media/screenshots" /></li>
                    <li><h:link class="menuitem" value="#{MLBean.getML('menu_lbl_halloffame')}" outcome="/sites/highscore/highscore" /></li>
                </ul>
            </li>
            <li><a href="#">#{MLBean.getML('menu_lbl_project')}</a>
                <ul>
                    <li><a class="menu_sourceforge" href="http://sourceforge.net/projects/darkdestiny/" target="new">Sourceforge</a></li>
                    <li><h:link class="menuitem" value="#{MLBean.getML('menu_lbl_bugtracker')}" outcome="/sites/bugtracker/bugs" /></li>
                    <li><h:link class="menuitem" value="#{MLBean.getML('menu_lbl_tasktracker')}" outcome="/sites/tasktracker/tasks" /></li>
                    <li><h:link class="menuitem" value="#{MLBean.getML('menu_lbl_releasenotes')}" outcome="/sites/releasenotes/releaseNotes" /></li>
                </ul>
            </li>
            <li><a href="#">#{MLBean.getML('menu_lbl_help')}</a>
                <ul>
                    <li><a href="http://www.thedarkdestiny.at/wiki/index.php/Hauptseite" target="new" class="menu_wiki">Wiki</a></li>
                    <li><h:link class="menuitem" value="#{MLBean.getML('menu_lbl_download')}" outcome="/sites/download" /></li>
                </ul>
            </li>
            <li><a class="language_#{MLBean.activeLanguage}" href="#">&#160;</a>
                <ul>
                    <li><h:commandLink class="menu_german" id="german" value="Deutsch" action="#{ServiceBean.setLanguage('DE','de')}"/></li>
                    <li><h:commandLink class="menu_english" id="english" value="English" action="#{ServiceBean.setLanguage('GB','en')}"/></li>
                </ul>
            </li>
        </ul>
    </h:form>
</ui:composition>