trunk/web.jsf/trunk/src/main/java/at/darkdestiny/web/bean/sites/StatusBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package at.darkdestiny.web.bean.sites;

import at.darkdestiny.core.model.StyleElement;
import at.darkdestiny.core.model.StyleToUser;
import at.darkdestiny.core.service.ProfileService;
import static at.darkdestiny.core.service.Service.styleElementDAO;
import at.darkdestiny.web.BeanUtilities;
import at.darkdestiny.web.dto.StatusBarItem;
import at.darkdestiny.web.view.menu.statusbar.style.basic.CreditBar;
import at.darkdestiny.web.view.menu.statusbar.style.basic.DevelopementBar;
import at.darkdestiny.web.view.menu.statusbar.style.basic.EnergyBar;
import at.darkdestiny.web.view.menu.statusbar.style.basic.FoodBar;
import at.darkdestiny.web.view.menu.statusbar.style.basic.PopulationBar;
import at.darkdestiny.web.view.menu.statusbar.style.basic.ResourceBar;
import com.google.common.base.Strings;
import com.google.common.collect.Lists;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

@ManagedBean(name = "StatusBean")
@RequestScoped
public class StatusBean {



    public String getBgColor(long value) {
        if (value > 0) {
            return "#00FF00";
        } else if (value < 0) {
            return "#FF0000";
        } else {
            return "#FFFF00";
        }
    }

   public PopulationBar getPopulationClazz() {
        try {
            return new PopulationBar();
        } catch (Exception ex) {
            Logger.getLogger(StatusBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    public FoodBar getFoodClazz() {
        try {
            return new FoodBar();
        } catch (Exception ex) {
            Logger.getLogger(StatusBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    public CreditBar getCreditClazz() {
        try {
            return new CreditBar();
        } catch (Exception ex) {
            Logger.getLogger(StatusBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    public EnergyBar getEnergyClazz() {
        try {
            return new EnergyBar();
        } catch (Exception ex) {
            Logger.getLogger(StatusBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }


    public ResourceBar getResourceClazz() {
        try {
            return new ResourceBar();
        } catch (Exception ex) {
            Logger.getLogger(StatusBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return null;
    }

    public DevelopementBar getDevelopementClazz() {
        try {
            return new DevelopementBar();
        } catch (Exception ex) {
            Logger.getLogger(StatusBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
}

trunk/web.jsf/trunk/src/main/webapp/sites/status/basic/creditBar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:a4j="http://richfaces.org/a4j"
                xmlns:rich="http://richfaces.org/rich"
                xmlns:dd="http://java.sun.com/jsf/composite/dd">

    <div class="col-lg-12">
        <a4j:outputPanel>
            <div class="creditbar_image col-lg-1">
                <rich:tooltip layout="block">
                    <dd:outputText value="#{MLBean.lang.sites.status.creditbar.label.credits}"/>
                </rich:tooltip>
            </div>
        </a4j:outputPanel>
        <div>
            <dd:formatValue styleClass="statusbar_label col-lg-8" 
                            value="#{StatusBean.creditClazz.globalCredits}" 
                            valueType="long" 
                            tooltip="true">
                <dd:outputText value="#{MLBean.lang.sites.status.creditbar.label.creditstotal}"/>
            </dd:formatValue>
        </div>

        <div style="margin: 0; padding: 0; color: green; border: 1px dotted green;">
            <dd:formatValue styleClass="statusbar_label col-lg-3"
                            value="#{StatusBean.creditClazz.planetCredits}" 
                            valueType="long" 
                            tooltip="true">
                <dd:outputText value="#{MLBean.lang.sites.status.creditbar.label.incomeplanet}"/>
            </dd:formatValue>
        </div>
    </div>

</ui:composition>


trunk/web.jsf/trunk/src/main/webapp/sites/status/basic/developementBar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:a4j="http://richfaces.org/a4j"
                xmlns:rich="http://richfaces.org/rich"
                xmlns:dd="http://java.sun.com/jsf/composite/dd">


    <div>
        <a4j:outputPanel>
            <div class="developmentbar_image">
                <rich:tooltip  layout="block">
                    <dd:outputText value="#{MLBean.lang.sites.status.developementbar.label.developementpoints}"/>
                </rich:tooltip>
            </div>
        </a4j:outputPanel>
        <div>
            <dd:formatValue styleClass="statusbar_label" value="#{StatusBean.developementClazz.globalDevelopement}" valueType="long" tooltip="true">
                <dd:outputText value="#{MLBean.lang.sites.status.developementbar.label.developementpointstotal}"/>
            </dd:formatValue>
        </div>

        <div>
            <dd:formatValue styleClass="statusbar_label" value="#{StatusBean.developementClazz.planetDevelopement}" valueType="long" tooltip="true">
                <dd:outputText value="#{MLBean.lang.sites.status.developementbar.label.developementpointsplanet}"/>
            </dd:formatValue>
        </div>
    </div>
</ui:composition>


trunk/web.jsf/trunk/src/main/webapp/sites/status/basic/energyBar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:a4j="http://richfaces.org/a4j"
                xmlns:dd="http://java.sun.com/jsf/composite/dd"
                xmlns:rich="http://richfaces.org/rich">

    <div class="row">
        <div class="col-lg-2 energy_icon">
            <dd:graphicImage name="#{StatusBean.energyClazz.icon}" tooltip="true">
                <dd:outputText value="#{MLBean.lang.sites.status.energybar.label.energy}"/>
            </dd:graphicImage>
        </div>
        <div class="col-lg-10">
            <div class="row statusbar_label">
                <a4j:outputPanel>
                    <div class="energybar_bar_production_now col-lg-12" style="z-index: #{StatusBean.energyClazz.productionNowZIndex}; width:#{StatusBean.energyClazz.barLengthProductionNow}px;">
                        <rich:tooltip layout="block">
                            <h:panelGrid columns="2" cellpadding="0" cellspacing="0">
                                <dd:outputText value="#{MLBean.lang.sites.status.energybar.label.productionnow}"/>
                                <dd:formatValue value="#{StatusBean.energyClazz.productionNow}" valueType="long" />
                                <dd:outputText value="#{MLBean.lang.sites.status.energybar.label.productionlater}"/>
                                <dd:formatValue value="#{StatusBean.energyClazz.productionLater}" valueType="long" />
                            </h:panelGrid>
                        </rich:tooltip>
                    </div>
                </a4j:outputPanel>
            </div>
            <div class="row statusbar_label">
                <a4j:outputPanel>
                    <div class="energybar_bar_production_later col-lg-12" style="z-index: 1; width:#{StatusBean.energyClazz.barLengthProductionLater}px;">
                        <rich:tooltip  layout="block">
                            <h:panelGrid columns="2" cellpadding="0" cellspacing="0">
                                <dd:outputText value="#{MLBean.lang.sites.status.energybar.label.productionnow}"/>
                                <dd:formatValue value="#{StatusBean.energyClazz.productionNow}" valueType="long" />
                                <dd:outputText value="#{MLBean.lang.sites.status.energybar.label.productionlater}"/>
                                <dd:formatValue value="#{StatusBean.energyClazz.productionLater}" valueType="long" />
                            </h:panelGrid>
                        </rich:tooltip>
                    </div>
                </a4j:outputPanel>
            </div>
            <div class="row statusbar_label">
                <a4j:outputPanel>
                    <div class="energybar_bar_consumption_now col-lg-12" style="z-index: #{StatusBean.energyClazz.consumptionNowZIndex}; width:#{StatusBean.energyClazz.barLengthConsumptionNow}px;">
                        <rich:tooltip  layout="block">
                            <h:panelGrid columns="2" cellpadding="0" cellspacing="0">
                                <dd:outputText value="#{MLBean.lang.sites.status.energybar.label.consumptionnow}"/>
                                <dd:formatValue value="#{StatusBean.energyClazz.consumptionNow}" valueType="long"/>
                                <dd:outputText value="#{MLBean.lang.sites.status.energybar.label.consumptionlater}"/>
                                <dd:formatValue value="#{StatusBean.energyClazz.consumptionLater}" valueType="long"/>
                            </h:panelGrid>
                        </rich:tooltip>
                    </div>
                </a4j:outputPanel>
            </div>
            <div class="row statusbar_label">
                <a4j:outputPanel>
                    <div class="energybar_bar_consumption_later col-lg-12" style="z-index: 1; width:#{StatusBean.energyClazz.barLengthConsumptionLater}px;">
                        <rich:tooltip  layout="block">
                            <h:panelGrid  columns="2" cellpadding="0" cellspacing="0">
                                <dd:outputText value="#{MLBean.lang.sites.status.energybar.label.consumptionnow}"/>
                                <dd:formatValue value="#{StatusBean.energyClazz.consumptionNow}" valueType="long"/>
                                <dd:outputText value="#{MLBean.lang.sites.status.energybar.label.consumptionlater}"/>
                                <dd:formatValue value="#{StatusBean.energyClazz.consumptionLater}" valueType="long"/>
                            </h:panelGrid>
                        </rich:tooltip>
                    </div>
                </a4j:outputPanel>
            </div>
        </div>
    </div>
</ui:composition>


trunk/web.jsf/trunk/src/main/webapp/sites/status/basic/foodBar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:a4j="http://richfaces.org/a4j"
                xmlns:rich="http://richfaces.org/rich"
                xmlns:dd="http://java.sun.com/jsf/composite/dd">
    <div class="row">
        <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
            <dd:status_tooltip
                resourceId="#{resourceId}"
                resourceImage="foodbar_image"
                showTransport="#{StatusBean.foodClazz.showTransport}"
                showTrade="#{StatusBean.foodClazz.showTrade}"
                showProduction="#{StatusBean.foodClazz.showProduction}"
                resourceName="#{MLBean.lang.sites.status.foodbar.label.food}"
                production="#{StatusBean.foodClazz.production}"
                consumption="#{StatusBean.foodClazz.consumption}"
                tradeIncoming="#{StatusBean.foodClazz.tradeIncoming}"
                tradeOutgoing="#{StatusBean.foodClazz.tradeOutgoing}"
                transportIncoming="#{StatusBean.foodClazz.transportIncoming}"
                transportOutgoing="#{StatusBean.foodClazz.transportOutgoing}"/>

        </div>
        <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
            <div class="row col-xs-12 col-sm-12 col-md-12 col-lg-12 statusbar_label">
                <a4j:outputPanel>
                    <div class="foodbar_bar_production" style="width:#{StatusBean.foodClazz.productionWidth}; z-index: #{StatusBean.foodClazz.productionZIndex}">
                        <rich:tooltip layout="block">
                            <h:panelGrid columns="2" cellpadding="0" cellspacing="0">
                                <dd:outputText value="#{MLBean.lang.sites.status.foodbar.label.production}"/>
                                <dd:formatValue value="#{StatusBean.foodClazz.production}" valueType="long"/>
                                <dd:outputText value="#{MLBean.lang.sites.status.foodbar.label.consumption}"/>
                                <dd:formatValue value="#{StatusBean.foodClazz.consumption}" valueType="long"/>
                            </h:panelGrid>
                        </rich:tooltip>
                    </div>
                </a4j:outputPanel>
            </div>
            <div class="row col-xs-12 col-sm-12 col-md-12 col-lg-12 statusbar_label">
                <a4j:outputPanel>
                    <div class="foodbar_bar_consumption" style="width:#{StatusBean.foodClazz.consumptionWidth}; z-index: #{StatusBean.foodClazz.consumptionZIndex}">
                        <rich:tooltip layout="block">
                            <h:panelGrid columns="2" cellpadding="0" cellspacing="0">
                                <dd:outputText value="#{MLBean.lang.sites.status.foodbar.label.production}"/>
                                <dd:formatValue value="#{StatusBean.foodClazz.production}" valueType="long"/>
                                <dd:outputText value="#{MLBean.lang.sites.status.foodbar.label.consumption}"/>
                                <dd:formatValue value="#{StatusBean.foodClazz.consumption}" valueType="long"/>
                            </h:panelGrid>
                        </rich:tooltip>
                    </div>
                </a4j:outputPanel>
            </div>
            <div class="row col-xs-12 col-sm-12 col-md-12 col-lg-12 statusbar_label">
                <a4j:outputPanel>
                    <div class="foodbar_bar_stock" style="width:#{StatusBean.foodClazz.stockWidth}; background-color: red;">
                        <rich:tooltip layout="block">
                            <dd:outputText value="statusbar_pop_storeusage" params="#{FormatBean.format(StatusBean.foodClazz.stockPercentage, 'double', '2', 'normal', 'false')}%,#{FormatBean.format(StatusBean.foodClazz.stockMax, 'long', '0', 'normal', 'false')}"/>
                        </rich:tooltip>
                    </div>
                </a4j:outputPanel>
            </div>
            <div class="row statusbar_label col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="">
                    <dd:status_stock width="#{StatusBean.foodClazz.stockWidth}"
                                     change="#{StatusBean.foodClazz.production - StatusBean.foodClazz.consumption +
                                               StatusBean.foodClazz.tradeIncoming - StatusBean.foodClazz.tradeOutgoing +
                                               StatusBean.foodClazz.transportIncoming - StatusBean.foodClazz.transportOutgoing }"
                                     maxStock="#{FormatBean.format(StatusBean.foodClazz.stockMax, 'long', '0', 'normal', 'false')}"
                                     percentage="#{FormatBean.format(StatusBean.foodClazz.stockPercentage, 'double', '2', 'normal', 'false')}%">
                    </dd:status_stock>
                </div>
            </div>
        </div>
    </div>
</ui:composition>


trunk/web.jsf/trunk/src/main/webapp/sites/status/basic/populationBar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:dd="http://java.sun.com/jsf/composite/dd"
                xmlns:a4j="http://richfaces.org/a4j"
                xmlns:rich="http://richfaces.org/rich">

    <div class="row">
        <c:if test="${StatusBean.populationClazz.morale ge 100}">
            <a4j:outputPanel>
                <div class="populationbar_morale_image_verygood col-xs-2 col-sm-2 col-md-2 col-lg-2">
                    <rich:tooltip layout="block">
                        <dd:outputText value="#{MLBean.lang.sites.status.populationbar.label.morale}"/>
                        <h:outputText value=": " escape="false"/>
                        <dd:formatValue value="#{StatusBean.populationClazz.morale}" valueType="long"/>
                    </rich:tooltip>
                </div>
            </a4j:outputPanel>
        </c:if>
        <c:if test="${(StatusBean.populationClazz.morale ge 75) and (StatusBean.populationClazz.morale le 100)}">
            <div class="populationbar_morale_image_good col-xs-2 col-sm-2 col-md-2 col-lg-2"/>
        </c:if>
        <c:if test="${(StatusBean.populationClazz.morale ge 50) and (StatusBean.populationClazz.morale le 75)}">
            <div class="populationbar_morale_image_equal col-xs-2 col-sm-2 col-md-2 col-lg-2"/>
        </c:if>
        <c:if test="${StatusBean.populationClazz.morale le 50}">
            <a4j:outputPanel>
                <div class="populationbar_morale_image_bad col-xs-2 col-sm-2 col-md-2 col-lg-2">
                    <rich:tooltip layout="block">
                        <dd:outputText value="#{MLBean.lang.sites.status.populationbar.label.morale}"/>
                        <h:outputText value=": " escape="false"/>
                        <dd:formatValue value="#{StatusBean.populationClazz.morale}" valueType="long"/>
                    </rich:tooltip>
                </div>
            </a4j:outputPanel>
        </c:if>
        <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 statusbar_label">
                    <dd:formatValue value="#{StatusBean.populationClazz.population}" valueType="long" tooltip="true">
                        <dd:outputText value="#{MLBean.lang.sites.status.populationbar.label.population}"/>
                    </dd:formatValue>
                </div>
            </div>
            <div class="row">
            <c:if test="${StatusBean.populationClazz.populationChange ge 0}">
                <div class="populationbar_growth_plus col-xs-2 col-sm-2 col-md-2 col-lg-2"/>
            </c:if>
            <c:if test="${StatusBean.populationClazz.populationChange lt 0}">
                <div class="populationbar_growth_minus col-xs-2 col-sm-2 col-md-2 col-lg-2"/>
            </c:if>
                <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10 statusbar_label">
                    <dd:formatValue value="#{StatusBean.populationClazz.populationChange}" valueType="long" tooltip="true">
                        <h:panelGrid styleClass="tooltip_text" columns="2" cellpadding="0" cellspacing="0">
                            <dd:outputText value="#{MLBean.lang.sites.status.populationbar.label.growh}"/>
                            <dd:formatValue value="#{StatusBean.populationClazz.growthPopulation}" valueType="long"/>
                            <dd:outputText value="#{MLBean.lang.sites.status.populationbar.label.migration}"/>
                            <dd:formatValue value="#{StatusBean.populationClazz.migration}" valueType="long"/>
                        </h:panelGrid>
                    </dd:formatValue>
                </div>
            </div>
        </div>
    </div>


</ui:composition>


trunk/web.jsf/trunk/src/main/webapp/sites/status/basic/rawResourceBar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:c="http://java.sun.com/jsp/jstl/core">

    <h:panelGrid cellpadding="0" cellspacing="0" columns="1">
        <c:forEach items="#{StatusBean.resourceClazz.rawResourceIds}" var="resourceId" >
            <h:column>
                <c:if test="#{StatusBean.resourceClazz.getRessourceBarEntry(resourceId).showResource}">
                    <ui:include src="rawResourceBarEntry.xhtml">
                        <ui:param name="resourceId" value="#{resourceId}"/>
                    </ui:include>
                </c:if>
            </h:column>
        </c:forEach>
    </h:panelGrid>

</ui:composition>


trunk/web.jsf/trunk/src/main/webapp/sites/status/basic/rawResourceBarEntry.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:rich="http://richfaces.org/rich"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:a4j="http://richfaces.org/a4j"
                xmlns:dd="http://java.sun.com/jsf/composite/dd"
                xmlns:c="http://java.sun.com/jsp/jstl/core">

    <div>

        <dd:status_tooltip
            resourceId="#{resourceId}"
            resourceImage="#{StatusBean.resourceClazz.getRessourceBarEntry(resourceId).getStyleClazz()}"
            showTransport="#{StatusBean.resourceClazz.getRessourceBarEntry(resourceId).showTransport}"
            showTrade="#{StatusBean.resourceClazz.getRessourceBarEntry(resourceId).showTrade}"
            showProduction="#{StatusBean.resourceClazz.getRessourceBarEntry(resourceId).showProduction}"
            resourceName="#{StatusBean.resourceClazz.getRessourceBarEntry(resourceId).resourceName}"
            production="#{StatusBean.resourceClazz.getRessourceBarEntry(resourceId).production}"
            consumption="#{StatusBean.resourceClazz.getRessourceBarEntry(resourceId).consumption}"
            tradeIncoming="#{StatusBean.resourceClazz.getRessourceBarEntry(resourceId).tradeIncoming}"
            tradeOutgoing="#{StatusBean.resourceClazz.getRessourceBarEntry(resourceId).tradeOutgoing}"
            transportIncoming="#{StatusBean.resourceClazz.getRessourceBarEntry(resourceId).transportIncoming}"
            transportOutgoing="#{StatusBean.resourceClazz.getRessourceBarEntry(resourceId).transportOutgoing}"/>

        <div>
            <dd:formatValue value="#{StatusBean.resourceClazz.getRessourceBarEntry(resourceId).ressStock}" valueType="long"/>
        </div>
    </div>

</ui:composition>


trunk/web.jsf/trunk/src/main/webapp/sites/status/basic/resourceBar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:c="http://java.sun.com/jsp/jstl/core">

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-2 col-lg-12">
            <h:panelGrid cellpadding="0" cellspacing="0" columns="1">
                <c:forEach items="#{StatusBean.resourceClazz.resourceIds}" var="resourceId" >
                    <h:column>
                        <c:if test="#{StatusBean.resourceClazz.getRessourceBarEntry(resourceId).showResource}">
                            <ui:include src="resourceBarEntry.xhtml">
                                <ui:param name="resourceId" value="#{resourceId}"/>
                            </ui:include>
                        </c:if>
                    </h:column>
                </c:forEach>
            </h:panelGrid>
        </div>
    </div>
</ui:composition>

trunk/web.jsf/trunk/src/main/webapp/sites/status/basic/richfacesEnergyBar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" 
                xmlns:a4j="http://richfaces.org/a4j" 
                xmlns:dd="http://java.sun.com/jsf/composite/dd" 
                xmlns:h="http://java.sun.com/jsf/html" 
                xmlns:rich="http://richfaces.org/rich" 
                xmlns:ui="http://java.sun.com/jsf/facelets">

    <h:panelGroup id="StatusEnergy" 
                  layout="block"
                  styleClass="col-xs-20 col-sm-20 col-md-20 col-lg-20 textFloatRight"
                  style="padding-bottom: 5px;">

        <a4j:outputPanel id="EnergyTooltipPanel"
                         layout="block">
            <rich:tooltip id="EnergyTooltip" 
                          layout="block">
                <dd:outputText id="EnergyTooltipText" 
                               value="#{MLBean.lang.sites.status.energybar.label.energy}" />
            </rich:tooltip>
        </a4j:outputPanel>

        <h:panelGroup id="EnergyIconGroup" 
                      styleClass="col-lg-5 row">
            <dd:graphicImage id="EnergyIcon" name="#{StatusBean.energyClazz.icon}" 
                             tooltip="true">
                <dd:outputText value="#{MLBean.lang.sites.status.energybar.label.energy}" />
            </dd:graphicImage>
        </h:panelGroup>

        <h:panelGroup styleClass="col-lg-15 textFloatRight">
            <dd:outputText value="#{MLBean.lang.sites.status.energybar.label.productionnow}"/>
            <dd:formatValue value="#{StatusBean.energyClazz.productionNow}" valueType="long" />
            <dd:outputText value="#{MLBean.lang.sites.status.energybar.label.productionlater}"/>
            <dd:formatValue value="#{StatusBean.energyClazz.productionLater}" valueType="long" />

            <dd:formatValue id="EnergyPlanet" 
                            styleClass="col-lg-20 row statusDigits" 
                            value="#{StatusBean.creditClazz.planetCredits}" 
                            valueType="long" 
                            tooltip="true">
                <dd:outputText id="EmergyIncomePlanet" 
                               styleClass="col-lg-20 row themeBackgroundBlack textFloatRight " 
                               value="#{MLBean.lang.sites.status.creditbar.label.incomeplanet}"/>
            </dd:formatValue>
        </h:panelGroup>

    </h:panelGroup>

</ui:composition>


trunk/web.jsf/trunk/src/main/webapp/sites/status/basic/spacer-template.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:rich="http://richfaces.org/rich">

    <rich:panel styleClass="spacer_label_position">
        
        <ui:insert id="SpacerContent" name="spacerContent">
            <h:outputText value="#{MLBean.getML(MLBean.lang.sites.status.creditbar.label.credits)}"/>
        </ui:insert>
        
    </rich:panel>
    
</ui:composition>
