trunk/web.jsf/trunk/src/main/java/at/darkdestiny/web/bean/sites/BuildableBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package at.darkdestiny.web.bean.sites;

import at.darkdestiny.core.enumeration.EConstructionType;
import at.darkdestiny.core.model.PlanetConstruction;
import at.darkdestiny.core.model.ProductionOrder;
import at.darkdestiny.core.result.InConstructionEntry;
import at.darkdestiny.core.result.InConstructionResult;
import at.darkdestiny.core.result.ProductionBuildResult;
import at.darkdestiny.core.service.ConstructionService;
import at.darkdestiny.core.service.ProductionService;
import at.darkdestiny.core.service.Service;
import at.darkdestiny.web.SessionContextHolder;
import at.darkdestiny.web.dto.SessionContext;
import at.darkdestiny.web.view.BuildableViewData;
import at.darkdestiny.web.view.construction.ConstructionViewData;
import at.darkdestiny.web.view.construction.PlanetConstructionView;
import com.google.common.collect.Lists;
import com.google.common.collect.Maps;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.model.SelectItem;

/**
 *
 * @author LAZYPAD
 */
@ManagedBean(name = "BuildableBean")
@RequestScoped
public class BuildableBean implements JsfBean {

    private int constructCount = 0;
    private int constructionId = 0;

    public enum EBuildableViewType {

        ADMINISTRATION, ENERGY, CIVIL, INDUSTRY, MILITARY, SHIPS, GROUNDTROOPS
    }

    private static final Map<EBuildableViewType, List<EConstructionType>> types;

    static {
        types = Maps.newLinkedHashMap();
        types.put(EBuildableViewType.ADMINISTRATION, Lists.newArrayList(EConstructionType.ADMINISTRATION));
        types.put(EBuildableViewType.ENERGY, Lists.newArrayList(EConstructionType.ENERGY));
        types.put(EBuildableViewType.CIVIL, Lists.newArrayList(EConstructionType.ZIVIL));
        types.put(EBuildableViewType.INDUSTRY, Lists.newArrayList(EConstructionType.INDUSTRY));
        types.put(EBuildableViewType.MILITARY, Lists.newArrayList(EConstructionType.MILITARY, EConstructionType.PLANETARY_DEFENSE));
        types.put(EBuildableViewType.SHIPS, null);
        types.put(EBuildableViewType.GROUNDTROOPS, null);
    }

    private BuildableViewData viewData;

    public BuildableBean() {
    }

    @Override
    public BuildableViewData getViewData() {
        if (viewData == null) {
            viewData = new BuildableViewData();
            calcViewData();
        }
        return viewData;
    }

    private void calcViewData() {
        SessionContext sessionContext = SessionContextHolder.getSessionContext();
        int planetId = sessionContext.getSelectedPlanetId();
        int userId = sessionContext.getUser().getId();

        for (Map.Entry<EBuildableViewType, List<EConstructionType>> entry : types.entrySet()) {
            ProductionBuildResult pbr = null;
            if (entry.getKey().equals(EBuildableViewType.SHIPS)) {
                pbr = ProductionService.getProductionListShips(userId, planetId);
            } else if (entry.getKey().equals(EBuildableViewType.GROUNDTROOPS)) {
                pbr = ProductionService.getProductionListGroundTroops(userId, planetId);
            } else {
                pbr = ConstructionService.getConstructionListSorted(userId, planetId, entry.getValue());
            }
            this.viewData.addProductionBuildResult(entry.getKey(), pbr);
        }

    }



    /**
     * @return the constructCount
     */
    public int getConstructCount() {
        return constructCount;
    }

    /**
     * @param constructCount the constructCount to set
     */
    public void setConstructCount(int constructCount) {
        this.constructCount = constructCount;
    }

    /**
     * @return the constructionId
     */
    public int getConstructionId() {
        return constructionId;
    }

    /**
     * @param constructionId the constructionId to set
     */
    public void setConstructionId(int constructionId) {
        this.constructionId = constructionId;
    }

}

trunk/web.jsf/trunk/src/main/java/at/darkdestiny/web/bean/sites/ChatBean.java
/*
 * JBoss, Home of Professional Open Source
 * Copyright 2013, Red Hat, Inc. and individual contributors
 * by the @authors tag. See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package at.darkdestiny.web.bean.sites;

import at.darkdestiny.core.model.User;
import at.darkdestiny.web.BeanUtilities;
import at.darkdestiny.web.SessionContextHolder;
import at.darkdestiny.web.dto.ChatEntry;
import at.darkdestiny.web.dto.Chats;
import com.google.common.base.Strings;
import com.google.common.collect.Lists;
import com.google.common.collect.Maps;
import java.awt.Color;
import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.Set;
import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.model.SelectItem;
import org.richfaces.application.push.TopicKey;
import org.richfaces.application.push.TopicsContext;
import org.richfaces.log.Logger;
import org.richfaces.log.RichfacesLogger;

/**
 * Sends message to topic using TopicsContext.
 *
 * @author <a href="http://community.jboss.org/people/lfryc">Lukas Fryc</a>
 */
@ApplicationScoped
@ManagedBean(name = "ChatBean")
public class ChatBean {

    public static final String PUSH_TOPICS_CONTEXT_TOPIC = "pushTopicsContext";

    private Logger log = RichfacesLogger.WEBAPP.getLogger();

    private String message = "";

    private Map<User, Color> chatColors = Maps.newHashMap();
    /*
     * (non-Javadoc)
     *
     * @see org.richfaces.demo.push.MessageProducer#sendMessage()
     */

    public void sendMessage(String topicName) throws Exception {
        try {

            if (Strings.isNullOrEmpty(message)) {
                return;
            }
            TopicKey topicKey = new TopicKey(topicName);
            TopicsContext topicsContext = TopicsContext.lookup();
            topicsContext.publish(new TopicKey("chat"), "message");

            Chats.addChatEntry(topicKey, new ChatEntry(message));

            message = "";

            log.info("published update event to topic : " + topicName);
        } catch (Exception e) {
            log.info("Sending push message using TopicContext failed (" + e.getMessage()
                    + ") - operation will be repeated in few seconds");
            e.printStackTrace();
            if (log.isDebugEnabled()) {
                log.debug(e);
            }
        }
    }

    public void setColor(String colorString) {
        Color color = Color.decode(colorString);
        User user = BeanUtilities.getLoggedUser();
        chatColors.remove(user);
        chatColors.put(user, color);
    }

    public List<SelectItem> getColorSelect() {
        List<SelectItem> options = Lists.newArrayList();

        addOption(options, Color.RED);
        addOption(options, Color.GREEN);
        addOption(options, Color.BLUE);
        addOption(options, Color.YELLOW);
        addOption(options, Color.MAGENTA);

        return options;
    }

    public void addOption(List<SelectItem> options, Color c) {
        String hex = getHexValue(c);
        options.add(new SelectItem(hex, hex));
    }

    public String getHexValue(Color c) {

        return "#" + Integer.toHexString(c.getRGB()).substring(2);
    }

    public List<String> getMessages(String topic) {

        Color c;
        if (BeanUtilities.getLoggedUser() != null) {
            c = chatColors.get(BeanUtilities.getLoggedUser());
            if (c == null) {
                c = genRandomColor();
                chatColors.put(BeanUtilities.getLoggedUser(), c);
            }
        } else {
            String sessionId = SessionContextHolder.getSessionId();
            String numberString = "";
            for (int i = 0; i < sessionId.length(); i++) {
                numberString += Character.getNumericValue(sessionId.charAt(i));
            }
            if (numberString.length() > 12) {
                numberString = numberString.substring(0, 12);
            }
            long number = Long.valueOf(numberString);
            int r = (int) (number % 254);
            int g = (int) (number % 123);
            int b = (int) (number % 12);
            if (r < 22 || g < 22 || b < 22) {
                r = 134;
                g = 212;
            }

            c = new Color(r, g, b);
        }

        TopicKey topicKey = new TopicKey(topic);
        return Chats.getMessages(topicKey, c);
    }

    private Color genRandomColor() {

        Random rand = new Random();
        float r = rand.nextFloat();
        float g = rand.nextFloat();
        float b = rand.nextFloat();

        return new Color(r, g, b);
    }

    public String getMessagesAsTextAreaString(String topic) {

        StringBuilder stringBuilder = new StringBuilder();
        for (String s : getMessages(topic)) {
            stringBuilder.append(s);
            stringBuilder.append("<BR/>");
        }
        return stringBuilder.toString();
    }

    public int getInterval() {
        return 5000;
    }

    public Set<TopicKey> getTopics() {
        return Chats.getTopics();
    }

    /*
     * (non-Javadoc)
     *
     * @see org.richfaces.demo.push.MessageProducer#finalizeProducer()
     */
    public void finalizeProducer() {
    }

    /**
     * @return the message
     */
    public String getMessage() {
        return message;
    }

    /**
     * @param message the message to set
     */
    public void setMessage(String message) {
        this.message = message;
    }
}

trunk/web.jsf/trunk/src/main/java/at/darkdestiny/web/bean/sites/ConstructionBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package at.darkdestiny.web.bean.sites;

import at.darkdestiny.core.enumeration.EConstructionType;
import at.darkdestiny.core.model.PlanetConstruction;
import at.darkdestiny.core.model.ProductionOrder;
import at.darkdestiny.core.result.InConstructionEntry;
import at.darkdestiny.core.result.InConstructionResult;
import at.darkdestiny.core.result.ProductionBuildResult;
import at.darkdestiny.core.service.ConstructionService;
import at.darkdestiny.core.service.ProductionService;
import at.darkdestiny.core.service.Service;
import at.darkdestiny.web.SessionContextHolder;
import at.darkdestiny.web.dto.SessionContext;
import at.darkdestiny.web.view.construction.ConstructionViewData;
import at.darkdestiny.web.view.construction.PlanetConstructionView;
import com.google.common.collect.Lists;
import com.google.common.collect.Maps;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.model.SelectItem;
import javax.faces.event.AjaxBehaviorEvent;

/**
 *
 * @author LAZYPAD
 */
@ManagedBean(name = "ConstructionBean")
@RequestScoped
public class ConstructionBean implements JsfBean {

    private int constructCount = 0;
    private int constructionId = 0;


    private ConstructionViewData viewData;

    public ConstructionBean() {
    }

    public void buildConstructions() {
        SessionContext sessionContext = SessionContextHolder.getSessionContext();
        int planetId = sessionContext.getSelectedPlanetId();
        int userId = sessionContext.getUser().getId();

        if (this.constructionId > 0 && this.constructCount > 0) {
            ConstructionService.buildBuilding(userId, planetId,
                    constructionId, constructCount);

            this.constructCount = 0;
            this.constructionId = 0;
        }
        this.calcViewData();
    }

    public void updateIdle() {
        for (EConstructionType type : EConstructionType.values()) {
            for (PlanetConstructionView pcv : viewData.getConstructionEntries(type)) {
                Service.planetConstructionDAO.update(pcv.getPlanetConstruction());
            }
        }
    }

    @Override
    public ConstructionViewData getViewData() {
        if (viewData == null) {
            calcViewData();
        }
        return viewData;
    }

    private void calcViewData() {
        SessionContext sessionContext = SessionContextHolder.getSessionContext();
        int planetId = sessionContext.getSelectedPlanetId();
        int userId = sessionContext.getUser().getId();

        this.viewData = new ConstructionViewData();
        InConstructionResult icr = ConstructionService.findRunnigConstructions(planetId);
        List<InConstructionEntry> constructions = icr.getEntries();
        this.viewData.setInConstructionEntires(constructions);

        TreeMap<EConstructionType, TreeMap<Integer, ArrayList<PlanetConstruction>>> planetConstructions = ConstructionService.findPlanetConstructions(planetId);
        this.viewData.setPlanetConstructions(planetConstructions);


    }

    public ArrayList<SelectItem> getPriorityOptions() {
        ArrayList<SelectItem> result = Lists.newArrayList();

        for (int i = 0; i < 10; i++) {
            result.add(new SelectItem(i, String.valueOf(i)));
        }
        return result;

    }

    public void updatePriorities() {
        System.out.println("update constrcution priorities");
        for (InConstructionEntry entry : this.viewData.getInConstructionEntries()) {
            ProductionOrder productionOrder = Service.productionOrderDAO.findById(entry.getOrder().getId());
            productionOrder.setPriority(entry.getOrder().getPriority());
            Service.productionOrderDAO.update(productionOrder);
        }
        this.calcViewData();
    }

    /**
     * @return the constructCount
     */
    public int getConstructCount() {
        return constructCount;
    }

    /**
     * @param constructCount the constructCount to set
     */
    public void setConstructCount(int constructCount) {
        this.constructCount = constructCount;
    }

    /**
     * @return the constructionId
     */
    public int getConstructionId() {
        return constructionId;
    }

    /**
     * @param constructionId the constructionId to set
     */
    public void setConstructionId(int constructionId) {
        this.constructionId = constructionId;
    }

}

trunk/web.jsf/trunk/src/main/java/at/darkdestiny/web/bean/sites/JsfBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package at.darkdestiny.web.bean.sites;

import at.darkdestiny.web.view.ViewData;

/**
 *
 * @author Admin
 */
public interface JsfBean {


    public ViewData getViewData();
}

trunk/web.jsf/trunk/src/main/java/at/darkdestiny/web/bean/sites/MenuBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package at.darkdestiny.web.bean.sites;

import at.darkdestiny.core.model.MenuLink;
import at.darkdestiny.core.model.User;
import at.darkdestiny.core.model.UserData;
import at.darkdestiny.core.model.UserSettings;
import at.darkdestiny.core.service.Service;
import at.darkdestiny.core.viewbuffer.MenuBuffer;
import at.darkdestiny.web.BeanUtilities;
import com.google.common.collect.Lists;
import java.io.Serializable;
import java.util.ArrayList;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/**
 *
 * @author LAZYPAD
 */
@ManagedBean(name = "MenuBean")
@SessionScoped
public class MenuBean implements Serializable {

    public ArrayList<MenuLink> getMenu() {
        User user = BeanUtilities.getLoggedUser();
        UserData userData = Service.userDataDAO.findByUserId(user.getUserId());
        UserSettings userSettings = Service.userSettingsDAO.findByUserId(user.getUserId());

        ArrayList<MenuLink> result = Lists.newArrayList();

        for (MenuLink menuLink : MenuBuffer.getMenuLinks()) {
            if (menuLink.getUrl() == null) {
                continue;
            }
            if (menuLink.getLinkName().equals("menu_welcome") && (userData == null || !userSettings.getShowWelcomeSite())) {
                continue;
            }

            if (menuLink.getAdminOnly() && (!user.getAdmin())) {
                continue;
            }
            result.add(menuLink);
        }
        return result;
    }

    public String management() {
        System.out.println("management() invoked");
        return "/sites/management/template?faces-redirect=true";

    }

    public String messages() {
        System.out.println("messages() invoked");
        return "/sites/messages/template?faces-redirect=true";

    }
}

trunk/web.jsf/trunk/src/main/webapp/sites/chat/chat.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:rich="http://richfaces.org/rich"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:dd="http://java.sun.com/jsf/composite/dd">
    <h:head>

    </h:head>
    <h:body>
        <h:outputStylesheet library="basic"
                            name="css/sites/chat.css"/>
        <h:form>
            <rich:tabPanel switchType="ajax" id="tp" headerPosition="top">
                <a4j:repeat value="#{ChatBean.topics}" var="topic">
                    <rich:tab header="#{topic.topicName}">
                        <h:panelGrid columns="1">
                            <a4j:push address="chat">
                                <a4j:ajax event="dataavailable" render="chat" />
                            </a4j:push>
                            <a4j:outputPanel id="chat">
                                <h:outputText escape="false" value="#{ChatBean.getMessagesAsTextAreaString(topic.topicName)}"/>
                                <h:inputText value="#{ChatBean.message}"/>
                            </a4j:outputPanel>
                            <a4j:commandButton action="#{ChatBean.sendMessage(topic.topicAddress)}" value="Senden"/>
                            <h:panelGrid columns="#{ChatBean.colorSelect.size()}">
                                <c:forEach items="#{ChatBean.colorSelect}" var="color">
                                    <a4j:commandLink action="#{ChatBean.setColor(color.label)}">
                                        <div style="width:20px; height: 20px; background-color: #{color.label};"/>
                                    </a4j:commandLink>
                                </c:forEach>
                            </h:panelGrid>
                        </h:panelGrid>
                    </rich:tab>
                </a4j:repeat>
            </rich:tabPanel>
        </h:form>
    </h:body>
</html>

trunk/web.jsf/trunk/src/main/webapp/sites/chat/chat_1.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:rich="http://richfaces.org/rich"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:dd="http://java.sun.com/jsf/composite/dd">
    <h:head>

    </h:head>
    <h:body>
        <h:outputStylesheet library="basic"
                            name="css/sites/chat.css"/>
        <h:form>

            <h:panelGrid columns="1">
                <a4j:push id="pushJms" address="pushTopicsContext">
                    <a4j:ajax event="dataavailable" render="chat" />
                </a4j:push>
                <a4j:outputPanel id="chat">
                    <h:outputText escape="false" value="#{ChatBean.getMessagesAsTextAreaString('pushTopicsContext')}"/>
                    <h:inputText value="#{ChatBean.message}"/>
                </a4j:outputPanel>
                <a4j:commandButton action="#{ChatBean.sendMessage('pushTopicsContext')}" value="sendMessage"/>
            </h:panelGrid>
        </h:form>
    </h:body>
</html>

trunk/web.jsf/trunk/src/main/webapp/sites/chat/consumer.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:rich="http://richfaces.org/rich"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:dd="http://java.sun.com/jsf/composite/dd">
    <h:head>

    </h:head>
    <h:body>
        <h:form>

            <a4j:push id="pushJms" address="pushTopicsContext">
                <a4j:ajax event="dataavailable" render="uuid" />
            </a4j:push>
            <h:panelGrid columns="2">
                <h:outputLabel value="New UUID:" />
                <a4j:outputPanel id="uuid" layout="block">
                    #{pushBean.UUID}
                </a4j:outputPanel>
            </h:panelGrid>
        </h:form>
    </h:body>
</html>

trunk/web.jsf/trunk/src/main/webapp/sites/chat/template.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:rich="http://richfaces.org/rich"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:dd="http://java.sun.com/jsf/composite/dd">
    <h:head>
    </h:head>
    <h:body>
        <h:outputText value="#{PushConfiguration.isPushEnabled()}"/>
        <h:form>
            <a4j:commandButton action="#{TopicsContextMessageProducer.sendMessage()}" value="sendMessage"/>
        </h:form>
    </h:body>
</html>